### PR TITLE
Organize samples as submodules of a single `:sample` gradle module

### PR DESCRIPTION
**Pull request by MatthewTPage**
Handles #14 

Moves samples to be a submodule of `:samples`, making `:samples:groovy-android` and `:samples:kotlin-android`. Also moves `sample_specs.json` into the samples directory.

Testing done:
Did `./gradlew :samples:kotlin-android:gS :samples:groovy-android:gS` and autogenerated files appeared in the src directories.

### CODE REVIEW

**Comment by cortinico** [comment]
Hey @MatthewTPage sorry for the late review :(

So the code looks fine.
Can I ask you to rebase on top of master + include the `samples-generated-code` module inside you refactoring?

If you can't I can still take care of that :)

**Comment by MatthewTPage** [comment]
np on the delay. Happy to also include samples-generated-code. I'll work on it this weekend :)

**Comment by cortinico** [comment]
Awesome :)

**Comment by MatthewTPage** [comment]
@cortinico  howdy, sorry for the delay on coming back to this, slipped my mind. Updated with master and also updated the README with the new locations. If there's anything else to do lmk :)

**Comment by cortinico** [comment]
Looks great @MatthewTPage thanks 💪

**Pull request merged**
