### PR TITLE
Codecov fix

### PR DESCRIPTION
**Pull request by macisamuele**
The goal of this PR is to ideally fix codecov comments into PRs (nothing specific has been done yet).
Fixes: #61

NOTE: I'm not 100% confident yet about the change, unfortunately as we need to test codecov capability to comment on PR we need to have something published

### CODE REVIEW

**Comment by cortinico** [comment]
Seems like Codecov is still not publishing to the repo. Maybe @sjaensch can support here? Can you please check that the Codecov App has the proper access rights for this repo?

**Comment by sjaensch** [comment]
So sorry @cortinico , completely missed this one. :( The Codecov app has to be enabled for every repository, I just did it for swagger-gradle-codegen. Does it work now?

**Comment by macisamuele** [comment]
Rebased on master and updated github pre-merge workflow instead of travis file.

**Comment by cortinico** [comment]
> So sorry @cortinico , completely missed this one. :( The Codecov app has to be enabled for every repository, I just did it for swagger-gradle-codegen. Does it work now?

Don't worry @sjaensch. Maybe @macisamuele you can open a new PR? I think codecov has a webhook on new PR events.

**Comment by macisamuele** [comment]
@cortinico codecov comments on the PR once receives new data coming from a PR... That was the reason to not create a new branch.

As you approved the change, fell free to merge it in master

**Pull request merged**
